### ISSUE TITLE
IE11 warnings when serving prebuilt deployment

### ISSUE THREAD

**Issue by adamdoyle** [PolymerLabs/start-lit-element#5]
### Overview
I'm seeing console warnings in IE11.

### Steps to Reproduce:

1. Open [this Glitch](https://glitch.com/edit/#!/ie11-lit-element-warnings) on IE11
2. Press F12 to open developer tools
3. Open JS Console
4. Refresh page in browser
5. Observe warnings below:

![image](https://user-images.githubusercontent.com/728428/49960070-4b56b000-fedd-11e8-8f21-84549978bd6b.png)

### Note
I suspect it may actually be a polymer/tools bug, since I experienced the same issue in my own project.  However, my project's build configuration was mostly based on this one, so I'm not sure.

**Comment by ghost** [comment]
Thanks for raising it, will look at it when I'm near my Windows machine. 

* Do you happen to know if it is behaving properly in Edge?
* Is the [deployed firebase version](https://start-lit-element.firebaseapp.com/) giving you the same warnings as this glitch?

**Comment by adamdoyle** [comment]
- I'm seeing the same error in Edge (although the component seemingly "functions" correctly in both/all[?] browsers, aside from the console warnings)
- I'm seeing it with the deployed firebase as well

See screenshot, below, of Edge (left) and IE11 (right):
![image](https://user-images.githubusercontent.com/728428/50242378-1b555400-0398-11e9-8c42-0f6b5f3f8d21.png)

**Comment by adamdoyle** [comment]
The HTML referenced by the first warning (about the exclamation mark) is this:
```HTML
<!-- Load polyfills -->
<script>
  if (!window.customElements) {
    document.write('<!--');
  }
</script>
<script type="text/javascript"
        src="node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>
<!--! do not remove -->
<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js" defer="">
</script>
```
The exclamation mark in question, column 9 of line 15, is apparently the second exclamation point of 
 `<!--! do not remove -->`)

The second warning is about the closing `-->` of the same comment.

**Comment by adamdoyle** [comment]
Ok, so apparently it's already documented here:  https://github.com/Polymer/polymer-cli/issues/779

So not an issue with this repo.

**Comment by ghost** [comment]
Thanks for finding that! Added a known issue to the README on this repo.
